import { Camera, Check, ImagePlus, Repeat2, Shirt } from 'lucide-react';
import { AppBar, Button, handleTabKey, Page } from '../components/ui';
import type { OutfitDayPlan } from '../types';

export function OutfitPlanningScreen({ plans, activeDayIndex, onActiveDayChange, onPlanChange, onAddOutfit, onBack, onSkip, onToast }: { plans: OutfitDayPlan[]; activeDayIndex: number; onActiveDayChange: (index: number) => void; onPlanChange: (plan: OutfitDayPlan) => void; onAddOutfit: (dayNumber: number) => void; onBack: () => void; onSkip: () => void; onToast: (message: string) => void }) {
  const plan = plans[activeDayIndex];
  const addedPlans = plans.filter((item) => item.decision === 'added');
  const clothing = [...new Set(addedPlans.flatMap((item) => item.items.map((piece) => piece.replace(/^Reuse /, ''))))];
  return <Page className="outfit-page" labelledBy="outfit-title"><AppBar title="Outfit Planning" onBack={onBack} /><div className="outfit-body"><section className="outfit-heading"><span><Shirt aria-hidden="true" size={24} /></span><div><p className="eyebrow">Optional helper</p><h2 id="outfit-title">Plan enough, not extra</h2><p>Use activity context and reuse clothing across days. Skipping does not affect Smart Packing.</p></div></section><div className="day-tabs" role="tablist" aria-label="Outfit days">{plans.map((item, index) => <button id={`outfit-tab-${item.dayNumber}`} type="button" role="tab" aria-selected={index === activeDayIndex} aria-controls={`outfit-panel-${item.dayNumber}`} tabIndex={index === activeDayIndex ? 0 : -1} className={index === activeDayIndex ? 'day-tab--active' : ''} key={item.dayNumber} onClick={() => onActiveDayChange(index)} onKeyDown={(event) => handleTabKey(event, index, plans.length, onActiveDayChange)}>Day {item.dayNumber}</button>)}</div>
    <div className="day-tabpanel" id={`outfit-panel-${plan.dayNumber}`} role="tabpanel" aria-labelledby={`outfit-tab-${plan.dayNumber}`} tabIndex={0}><section className="outfit-card" aria-labelledby="outfit-day-title"><div className="outfit-card__heading"><div><small>Day {plan.dayNumber} activity</small><h3 id="outfit-day-title">{plan.activityContext}</h3></div><span className={`outfit-status outfit-status--${plan.decision}`}>{plan.decision === 'added' ? 'Added' : plan.decision === 'skipped' ? 'Skipped' : 'Suggested'}</span></div><div className="outfit-suggestion"><span>Suggested outfit</span>{plan.items.map((item) => <strong key={item}>{item}</strong>)}</div>{plan.decision === 'pending' ? <div className="outfit-decision"><Button type="button" onClick={() => onAddOutfit(plan.dayNumber)}>Add Outfit</Button><Button type="button" variant="tertiary" onClick={() => onPlanChange({ ...plan, decision: 'skipped' })}>Skip</Button></div> : null}
      <div className="photo-actions"><button type="button" onClick={() => { onPlanChange({ ...plan, photoAttached: true }); onToast('Photo captured for this outfit'); }}><Camera aria-hidden="true" size={17} /> Take Photo</button><button type="button" onClick={() => { onPlanChange({ ...plan, photoAttached: true }); onToast('Photo uploaded for this outfit'); }}><ImagePlus aria-hidden="true" size={17} /> Upload Photo</button></div>{plan.photoAttached ? <div className="photo-status"><Check aria-hidden="true" size={16} /> Outfit photo attached</div> : null}
      <label className="outfit-field"><span>Short notes</span><textarea name={`outfit-notes-${plan.dayNumber}`} autoComplete="off" placeholder="Example: Pack a light layer…" value={plan.notes} onChange={(event) => onPlanChange({ ...plan, notes: event.target.value })} /></label>
      <label className="outfit-field"><span><Repeat2 aria-hidden="true" size={16} /> Reuse clothing</span><select name={`outfit-reuse-${plan.dayNumber}`} value={plan.reuseItem} onChange={(event) => onPlanChange({ ...plan, reuseItem: event.target.value })}><option value="">No reuse selected</option>{plan.dayNumber > 1 ? <><option>Walking shoes — Day 1</option><option>Lightweight trousers — Day 1</option><option>Breathable top — Day 1</option></> : null}</select></label>{plan.reuseItem ? <div className="reuse-note"><Repeat2 aria-hidden="true" size={16} /><span>{plan.reuseItem} counts once in the final clothing quantity.</span></div> : null}
    </section>
    {clothing.length ? <section className="clothing-summary"><div className="section-heading"><h2>Final Clothing Packing</h2><span>Reuse consolidated</span></div>{clothing.slice(0, 6).map((item) => <div key={item}><span>{item}</span><strong>×1</strong></div>)}</section> : null}</div>
    <Button type="button" variant="secondary" fullWidth onClick={onSkip}>Skip Outfit Planning</Button>
  </div></Page>;
}
