import { Bell, CalendarClock, UsersRound } from 'lucide-react';
import type { ReactNode } from 'react';
import { AppBar, Button, Page } from '../components/ui';
import type { ReminderSettings, TravelMode } from '../types';

export function PackingRemindersScreen({ mode, settings, onChange, onBack, onSave }: { mode: TravelMode; settings: ReminderSettings; onChange: (settings: ReminderSettings) => void; onBack: () => void; onSave: () => void }) {
  const toggle = (key: keyof ReminderSettings) => onChange({ ...settings, [key]: !settings[key] });
  const allOff = !settings.threeDays && !settings.oneDay && !settings.departureDay && (mode !== 'group' || !settings.sharedAlerts);
  return <Page className="reminders-page" labelledBy="reminders-title"><AppBar title="Packing Reminders" onBack={onBack} /><div className="reminders-body"><section className="reminders-heading"><span><Bell aria-hidden="true" size={23} /></span><div><p className="eyebrow">Milestone-based</p><h2 id="reminders-title">Helpful, not noisy</h2><p>Reminders focus on the packing decisions that matter at each stage.</p></div></section><section className="reminder-list" aria-label="Reminder settings"><ReminderToggle icon={<CalendarClock aria-hidden="true" size={19} />} title="3 Days Before" description={mode === 'group' ? 'Remaining Needed items and unresolved Shared items.' : 'Remaining Needed items and unchecked essentials.'} checked={settings.threeDays} onToggle={() => toggle('threeDays')} /><ReminderToggle icon={<Bell aria-hidden="true" size={19} />} title="1 Day Before" description={mode === 'group' ? 'Main reminder for Needed, Shared and overall progress.' : 'Main reminder for Needed items and overall progress.'} checked={settings.oneDay} onToggle={() => toggle('oneDay')} /><ReminderToggle icon={<CalendarClock aria-hidden="true" size={19} />} title="Departure Day" description="Critical essentials only — not every optional item." checked={settings.departureDay} onToggle={() => toggle('departureDay')} />{mode === 'group' ? <ReminderToggle icon={<UsersRound aria-hidden="true" size={19} />} title="Shared Packing Alerts" description="Unassigned items or uncovered quantities only." checked={settings.sharedAlerts} onToggle={() => toggle('sharedAlerts')} /> : null}</section>{mode === 'group' ? <p className="reminder-footnote">Checking an item does not notify the whole group.</p> : null}<Button type="button" variant="tertiary" fullWidth disabled={allOff} onClick={() => onChange({ threeDays: false, oneDay: false, departureDay: false, sharedAlerts: false })}>Turn All Off</Button><div className="sticky-action"><Button type="button" fullWidth onClick={onSave}>Save Reminders</Button></div></div></Page>;
}

function ReminderToggle({ icon, title, description, checked, onToggle }: { icon: ReactNode; title: string; description: string; checked: boolean; onToggle: () => void }) {
  return <button className="reminder-toggle" type="button" role="switch" aria-checked={checked} onClick={onToggle}><span className="reminder-toggle__icon">{icon}</span><span><strong>{title}</strong><small>{description}</small></span><span className={`switch ${checked ? 'switch--on' : ''}`} aria-hidden="true"><i /></span></button>;
}
